#!/bin/bash
# this script walls if a user logs in so you can then run pkill -u or something

IFS=$'\n' users_list=($(awk -F: '$7 == "/bin/bash" {print $1}' /etc/passwd))

for str in ${users_list[@]}; do
  echo "wall 'user $str has logged in'" >> /home/$str/.bashrc
done
